name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: pmc-server-prod
  GKE_ZONE: us-west1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 'Create secret files'
      run: |
        mkdir -p ~/.config/
        touch firebase_secret_key.json
        touch pmc-server_master_key.json
        echo ${{ secrets.FIREBASE_AUTH }} >> .config/firebase_secret_key.json
        echo ${{ secrets.GCLOUD_AUTH }} >> .config/pmc-server_master_key.json

    - name: Build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ env.PROJECT_ID }}/pmc-server/pmc-server-prod:latest
    
    - id: 'Auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCLOUD_AUTH }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure kubectl
      run: |
        gcloud config set project ${{ env.PROJECT_ID }}
        gcloud config set compute/region ${{ env.GKE_ZONE }}
        gcloud containter clusters get-credentials ${{ env.GKE_CLUSTER }}

    - name: Apply
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
    
